spring:
  datasource:
    url: jdbc:mysql://mysql:3306/food?useSSL=false
    username: mysql
    password: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: none
              
management:
  endpoints:
    web:
      exposure:
        include: *
